# Site settings
title: Skyler's Space
email: skylerzhang@gmail.com
description: "js nodejs 前端 帝都 码农"
baseurl: "/blog"
url: "http://www.skylerzhang.com"
username: skylerzhang

    
# Build settings
markdown: kramdown
permalink: pretty
